# Generated by Django 6.0.2 on 2026-02-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.URLField(),
        ),
    ]
