# Generated by Django 6.0.2 on 2026-03-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intu', '0003_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='upload',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upload',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
