# Generated by Django 6.0.2 on 2026-03-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('warehouse_manager', 'Warehouse Manager'), ('store_manager', 'Store Manager'), ('admin', 'Admin')], default='warehouse_manager', max_length=20),
        ),
    ]
